version: "2.1"
services:
    CPX_0:
      image: quay.io/citrix/citrix-k8s-cpx-ingress:14.1-21.57
      ports:
        -  9443
        -  22
        -  9080
        -  161/udp
      tty: true
      cap_add:
        - NET_ADMIN
      ulimits:
        core: -1
      volumes:
        - /root/test:/cpx
      environment:
        -  CPX_CORES=2
        -  EULA=yes
      networks:
        -  bridge
        -  default
        