########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.91.0/24

########################### SECRETS
secrets:
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim
include:

########################### SERVICES
  # PREFIX udms = Ultimate Docker Media Server
  # HOSTNAME=docker1 - defined in .env

  # CORE
  - /home/rfaulkner/docker/socket-proxy.yml
  - /home/rfaulkner/docker/portainer.yml
  # - /home/rfaulkner/docker/cpx.yml
  - /home/rfaulkner/docker/dozzle.yml
  - /home/rfaulkner/docker/homepage.yml
  # MEDIA
  - /home/rfaulkner/docker/plex.yml
  # DOWNLOADERS
  - /home/rfaulkner/docker/qbittorrent.yml
  - /home/rfaulkner/docker/deluge.yml
  - /home/rfaulkner/docker/transmission.yml
  # INDEXERS
  - /home/rfaulkner/docker/prowlarr.yml
  - /home/rfaulkner/docker/flaresolverr.yml
  # PVRs
  - /home/rfaulkner/docker/radarr.yml
  - /home/rfaulkner/docker/sonarr.yml
  # COMPLEMENTARY APPS
  - /home/rfaulkner/docker/bazarr.yml
  - /home/rfaulkner/docker/tautulli.yml
  - /home/rfaulkner/docker/overseer.yml
  # MONITORING
  - /home/rfaulkner/docker/uptime-kuma.yml
  - /home/rfaulkner/docker/watchtower.yml
  # DATABASES
  #  - /home/rfaulkner/docker/mariadb.yml
  # MAINTENANCE
  - /home/rfaulkner/docker/docker-gc.yml
  - /home/rfaulkner/docker/duplicati.yml
