########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.91.0/24

########################### SECRETS
secrets:
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim
include:

########################### SERVICES
  # PREFIX udms = Ultimate Docker Media Server
  # HOSTNAME=docker1 - defined in .env

  # CORE
  - /home/rfaulkner/docker/compose/$HOSTNAME/socket-proxy.yml
  - /home/rfaulkner/docker/compose/$HOSTNAME/portainer.yml
  # - /home/rfaulkner/docker/compose/$HOSTNAME/cpx.yml
  - /home/rfaulkner/docker/compose/$HOSTNAME/dozzle.yml
  - /home/rfaulkner/docker/compose/$HOSTNAME/homepage.yml
  # MEDIA
  - /home/rfaulkner/docker/compose/$HOSTNAME/plex.yml
  # DOWNLOADERS
  - /home/rfaulkner/docker/compose/$HOSTNAME/qbittorrent.yml
  - /home/rfaulkner/docker/compose/$HOSTNAME/transmission.yml
  # INDEXERS
  - /home/rfaulkner/docker/compose/$HOSTNAME/prowlarr.yml
  - /home/rfaulkner/docker/compose/$HOSTNAME/flaresolverr.yml
  # PVRs
  - /home/rfaulkner/docker/compose/$HOSTNAME/radarr.yml
  - /home/rfaulkner/docker/compose/$HOSTNAME/sonarr.yml
  # COMPLEMENTARY APPS
  - /home/rfaulkner/docker/compose/$HOSTNAME/bazarr.yml
  - /home/rfaulkner/docker/compose/$HOSTNAME/tautulli.yml
  - /home/rfaulkner/docker/compose/$HOSTNAME/overseer.yml
  # MONITORING
  - /home/rfaulkner/docker/compose/$HOSTNAME/uptime-kuma.yml
  # DATABASES
  #  - /home/rfaulkner/docker/compose/$HOSTNAME/mariadb.yml
  # MAINTENANCE
  - /home/rfaulkner/docker/compose/$HOSTNAME/docker-gc.yml
  - /home/rfaulkner/docker/compose/$HOSTNAME/duplicati.yml
