########################### NETWORKS
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.91.0/24

########################### SECRETS
secrets:
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim
include:

########################### SERVICES
  # PREFIX udms = Ultimate Docker Media Server
  # HOSTNAME=docker1 - defined in .env

  # CORE
  - $DOCKERDIR/socket-proxy.yml
  - $DOCKERDIR/portainer.yml
  # - $DOCKERDIR/cpx.yml
  - $DOCKERDIR/dozzle.yml
  - $DOCKERDIR/homepage.yml
  # MEDIA
  - $DOCKERDIR/plex.yml
  # DOWNLOADERS
  - $DOCKERDIR/qbittorrent.yml
  - $DOCKERDIR/transmission.yml
  # INDEXERS
  - $DOCKERDIR/prowlarr.yml
  - $DOCKERDIR/flaresolverr.yml
  # PVRs
  - $DOCKERDIR/radarr.yml
  - $DOCKERDIR/sonarr.yml
  # COMPLEMENTARY APPS
  - $DOCKERDIR/bazarr.yml
  - $DOCKERDIR/tautulli.yml
  - $DOCKERDIR/overseer.yml
  # MONITORING
  - $DOCKERDIR/uptime-kuma.yml
  # DATABASES
  #  - $DOCKERDIR/mariadb.yml
  # MAINTENANCE
  - $DOCKERDIR/docker-gc.yml
  - $DOCKERDIR/duplicati.yml
