services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      # (optional) - CLI_ARGS=
    volumes:
      - /$DOCKERDIR/appdata/duplicati:/config
      - /mnt/data/backups:/backups
      - /home/rfaulkner:/source
    ports:
      - 8200:8200
    restart: unless-stopped
