---
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    volumes:
      - /$DOCKERDIR/appdata/jackett:/config
      - /mnt/data/torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
