version: '3'

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
    volumes:
     - $dockerdir/appdata/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

